### ISSUE TITLE
About comparative methods of language tasks

### ISSUE THREAD

**Issue by amaya382** [dayu11/Differentially-Private-Deep-Learning#2]
Hi,
I'd like to reproduce the experiments in Table 4.
And I could run Method RGP and RGP (N.P.) with this repository, but where is the proper code/code version for Method Full (N.P.) and DP-SGD?
I guess they use the original fairseq codebase or MC-BERT with opacus or pyvacy or sth like that.

**Comment by dayu11** [comment]
Hi,

For Full (N.P.), you can use the code in this repo: https://github.com/pytorch/fairseq/tree/master/examples/roberta. 

For DP-SGD, I'm afraid that there is no publicly available code. You can make the following changes to this repo to run experiments with DP-SGD. 

1. In fairseq/trainer.py, only add the original layers to the **params** list. 
2. Register forward/backward hookers for the original layers. The hookers are provided in fairseq/lrk_utils.py.
3. Run the normal forward process (without reparametrization).

I had implemented these but the code was removed during implementing RGP.

**Comment by amaya382** [comment]
Thank you for your quick and polite response :) I'll try it.

**Comment by dayu11** [comment]
> Thank you for your quick and polite response :) I'll try it.

Hi, I found an implementation of [DP-SGD](https://github.com/AnonymousAKES/Differentially-Private-Fine-tuning-of-Language-Models/tree/main/Language-Understanding) based on this repo when I go through ICLR2022 submissions. Hope this is still helpful after a month : ).

**Comment by amaya382** [comment]
Thank you for your information. It seems helpful!
