### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Ulricalang** [dayu11/Differentially-Private-Deep-Learning#6]
n = params[0].grad_batch.shape[0] AttributeError: 'Parameter' object has no attribute 'grad_batch'

**Comment by dayu11** [comment]
Thanks for the report. Could you please share the command you used and modifications to the code (if any)?

**Comment by dayu11** [comment]
Close this thread because it has been inactive for a long time. You are welcome to reopen it when you have more details.
